# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be5c2e36b62f2cc044aac1f67b19ebc4253f227d9c843b51b4358a4e89da86a9344bfc75fb182483f71eabba4432b230e653cfbbbcc1908c3fcd2f623f1229ab

test:
  secret_key_base: 20b6abef39fe8a1cc1b2d867f8aa5027492ed477e7f58fbafeade65764c4afcedca979e07605aba1ef4ebfb2820fa0faace8632bd31330b04462562ecd7b5329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
